name: goreleaser
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.5"
      - name: Authenticate with GitHub App
        id: gh-app-auth
        uses: kanmu/gh-app-auth@main
        with:
          app-id: 244816
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          account: kanmu
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.gh-app-auth.outputs.token }}
